### ISSUE TITLE
Unable to run on iOS.

### ISSUE THREAD

**Issue by KamalPixi** [nizwar/openvpn_flutter#1]
Automatically signing iOS for device deployment using specified development team in Xcode project: U5SKJ77***
Running pod install...                                           2,156ms
Running Xcode build...                                                  
Xcode build done.                                           21.0s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:E0E442E2-065A-4F8B-B31D-69A94578339A, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:EE9400E8-C8E0-4D83-80E6-88F69D743080, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:237CE7AF-55C6-4D51-B04A-71412794F353, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:3377881B-6CDA-4A39-8DEF-1AE6C4090F27, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:89F66751-A788-40D8-9422-A493F9F9F08E, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:5F8F7BD1-B5C3-4444-99DE-1EAFD4C66983, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:30D87E97-3F2B-403F-8EE2-64B3415BE8F8, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:1EFC4CCE-B5A6-4654-A098-8B99A8B41A65, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:2240D2CD-8391-4500-A1B8-77D2E6324E2E, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:0B0B6A4B-FECF-4606-A6A6-73F2F4BED83C, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:A92E7CC9-F04B-4174-B112-9C64FDAF8B07, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:C984324A-7EBD-40AC-8F41-364A55441F56, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:88E79761-821F-47B8-8FE9-8B8CC8D27F41, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:087781A1-1AA4-48E3-A2AD-240552076328, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:CCC3344D-7470-4110-83D2-02AA94B301AE, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:21019195-35CD-441B-92EE-4AC05741DD9F, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:C48AEB56-3F1C-4E75-950F-9A410BAABDE4, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:64726BB5-3E8E-4502-8710-2221A1ABD70C, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:90C7864B-D17A-4B07-BFF2-E84B5D6775AA, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:90CF9C8C-BA9B-4087-9B24-5EB4229E840F, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:5110A21C-27FE-429E-8C30-F65CDF995DA8, OS:15.0, name:iPod touch (7th generation) }
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/macbookpro/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/ios/Classes/OpenVPNFlutterPlugin.m:1:9: warning: non-portable path to
    file '"OpenVPNFlutterPlugin.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
    #import "OpenvpnFlutterPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~
            "OpenVPNFlutterPlugin.h"
    1 warning generated.
    ../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/lib/src/vpn_engine.dart:187:17: Error: The getter 'name' isn't defined for the
    class 'VPNStage'.
     - 'VPNStage' is from 'package:openvpn_flutter/src/vpn_engine.dart'
     ('../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/lib/src/vpn_engine.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
            element.name.trim().toLowerCase() ==
                    ^^^^
    Failed to package /Users/macbookpro/Desktop/ios/tumila.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the precompiled application for the device.

Error launching application on Kamal’s iPhone.

**Comment by KamalPixi** [comment]
Looking for a solution thank you.

**Comment by moumen14dz** [comment]
> Automatically signing iOS for device deployment using specified development team in Xcode project: U5SKJ77*** Running pod install... 2,156ms Running Xcode build... Xcode build done. 21.0s Failed to build iOS app Error output from Xcode build: ↳ --- xcodebuild: WARNING: Using the first of multiple matching destinations: { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device } { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device } { platform:iOS Simulator, id:E0E442E2-065A-4F8B-B31D-69A94578339A, OS:15.0, name:iPad (9th generation) } { platform:iOS Simulator, id:EE9400E8-C8E0-4D83-80E6-88F69D743080, OS:15.0, name:iPad Air (4th generation) } { platform:iOS Simulator, id:237CE7AF-55C6-4D51-B04A-71412794F353, OS:15.0, name:iPad Pro (9.7-inch) } { platform:iOS Simulator, id:3377881B-6CDA-4A39-8DEF-1AE6C4090F27, OS:15.0, name:iPad Pro (11-inch) (3rd generation) } { platform:iOS Simulator, id:89F66751-A788-40D8-9422-A493F9F9F08E, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) } { platform:iOS Simulator, id:5F8F7BD1-B5C3-4444-99DE-1EAFD4C66983, OS:15.0, name:iPad mini (6th generation) } { platform:iOS Simulator, id:30D87E97-3F2B-403F-8EE2-64B3415BE8F8, OS:15.0, name:iPhone 8 } { platform:iOS Simulator, id:1EFC4CCE-B5A6-4654-A098-8B99A8B41A65, OS:15.0, name:iPhone 8 Plus } { platform:iOS Simulator, id:2240D2CD-8391-4500-A1B8-77D2E6324E2E, OS:15.0, name:iPhone 11 } { platform:iOS Simulator, id:0B0B6A4B-FECF-4606-A6A6-73F2F4BED83C, OS:15.0, name:iPhone 11 Pro } { platform:iOS Simulator, id:A92E7CC9-F04B-4174-B112-9C64FDAF8B07, OS:15.0, name:iPhone 11 Pro Max } { platform:iOS Simulator, id:C984324A-7EBD-40AC-8F41-364A55441F56, OS:15.0, name:iPhone 12 } { platform:iOS Simulator, id:88E79761-821F-47B8-8FE9-8B8CC8D27F41, OS:15.0, name:iPhone 12 Pro } { platform:iOS Simulator, id:087781A1-1AA4-48E3-A2AD-240552076328, OS:15.0, name:iPhone 12 Pro Max } { platform:iOS Simulator, id:CCC3344D-7470-4110-83D2-02AA94B301AE, OS:15.0, name:iPhone 12 mini } { platform:iOS Simulator, id:21019195-35CD-441B-92EE-4AC05741DD9F, OS:15.0, name:iPhone 13 } { platform:iOS Simulator, id:C48AEB56-3F1C-4E75-950F-9A410BAABDE4, OS:15.0, name:iPhone 13 Pro } { platform:iOS Simulator, id:64726BB5-3E8E-4502-8710-2221A1ABD70C, OS:15.0, name:iPhone 13 Pro Max } { platform:iOS Simulator, id:90C7864B-D17A-4B07-BFF2-E84B5D6775AA, OS:15.0, name:iPhone 13 mini } { platform:iOS Simulator, id:90CF9C8C-BA9B-4087-9B24-5EB4229E840F, OS:15.0, name:iPhone SE (2nd generation) } { platform:iOS Simulator, id:5110A21C-27FE-429E-8C30-F65CDF995DA8, OS:15.0, name:iPod touch (7th generation) } ** BUILD FAILED **
> 
> Xcode's output: ↳ /Users/macbookpro/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/ios/Classes/OpenVPNFlutterPlugin.m:1:9: warning: non-portable path to file '"OpenVPNFlutterPlugin.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path] #import "OpenvpnFlutterPlugin.h" ^~~~~~~~~~~~~~~~~~~~~~~~ "OpenVPNFlutterPlugin.h" 1 warning generated. ../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/lib/src/vpn_engine.dart:187:17: Error: The getter 'name' isn't defined for the class 'VPNStage'. - 'VPNStage' is from 'package:openvpn_flutter/src/vpn_engine.dart' ('../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/lib/src/vpn_engine.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'. element.name.trim().toLowerCase() == ^^^^ Failed to package /Users/macbookpro/Desktop/ios/tumila. Command PhaseScriptExecution failed with a nonzero exit code note: Using new build system note: Planning note: Build preparation complete note: Building targets in parallel
> 
> Could not build the precompiled application for the device.
> 
> Error launching application on Kamal’s iPhone.

just go to sdk/flutter/.pub-cache/hosted/pub.dartlang.org/openvpn_flutter-1.1.0/lib/src/vpn_engine.dart:187:17 
and change
element.name.trim()    by  element.tostring.trim()

**Comment by KamalPixi** [comment]
Thank You @moumen14dz Problem solved. :)
