### ISSUE TITLE
PlayStore version not working.

### ISSUE THREAD

**Issue by bugrevealingbme** [nizwar/openvpn_flutter#10]
There is such an error in the PlayStore version. Is it a joke?
https://user-images.githubusercontent.com/22865739/154671658-31227443-acf2-4850-8099-073919dc85a7.mp4

**Comment by bugrevealingbme** [comment]
Fix:

gradle.properties > android.bundle.enableUncompressedNativeLibs=false
AndroidManifest > android:extractNativeLibs="true" in application tag

**Comment by nizwar** [comment]
Hi, Do you still have the problem?

**Comment by bugrevealingbme** [comment]
> Hi, Do you still have the problem?

No. This is the fix:

gradle.properties > android.bundle.enableUncompressedNativeLibs=false
AndroidManifest > android:extractNativeLibs="true" in application tag

**Comment by HarshMishra-3456** [comment]
I'm developing a VPN application in Flutter that works perfectly on Android, but on iOS, I encounter issues where the VPN connection immediately transitions from "connecting" to "disconnecting." Additionally, in the iOS system VPN settings, I see an error message stating "update required" for my app.

Here are some details about my setup:

Environment:

Flutter version: 3.24.4 Target iOS version: 15.0 Plugins Tested:

open_vpn_flutter wireguard_flutter Both plugins exhibit the same behavior on iOS even though the Android implementation is flawless.

Behavior:

On iOS, the VPN connection status quickly changes from connecting to disconnecting. The system VPN settings display an "update required" error for the app. Troubleshooting Steps:

Verified that all necessary permissions and entitlements are correctly configured in the iOS project (including Info.plist and VPN extension settings). Tested with both VPN protocols (OpenVPN and WireGuard), and the issue persists. Question: Has anyone encountered a similar issue or does anyone have suggestions on what might cause the "update required" error in iOS system VPN settings? Are there any additional configuration steps specific to iOS that might be missing? Any guidance to help resolve this problem would be greatly appreciated.

What I Tried and What I Expected:

I followed the entire process outlined in this GitHub issue where another user reported a similar problem. I also meticulously went through the open_vpn_flutter documentation, ensuring that all required iOS entitlements, VPN extension configurations, and Info.plist settings were correctly applied. I even attempted to replicate the configuration using wireguard_flutter as an alternative.

What I Expected to Happen: I expected the VPN connection on iOS to establish successfully—similar to how it works on Android—resulting in a stable VPN connection without interruptions. The app should have maintained a persistent connection, and the iOS system VPN settings should have recognized the VPN configuration without any errors.

What Actually Happened: Despite following all the prescribed steps, the VPN on iOS transitions immediately from "connecting" to "disconnecting." Additionally, in the iOS system settings, the VPN configuration shows an error message stating "update required." This issue persists regardless of using either open_vpn_flutter or wireguard_flutter, and the VPN simply fails to connect on iOS.

**Comment by mominrazashahid** [comment]
getting this error on set 

`android.bundle.enableUncompressedNativeLibs=false` in gradle.properties.

```
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > com.android.builder.errors.EvalIssueException: The option 'android.bundle.enableUncompressedNativeLibs' is deprecated.
     The current default is 'true'.
     It was removed in version 8.1 of the Android Gradle plugin.
```

**Comment by EgorMarkor** [comment]
Brother, update the documentation. It is very old

**Comment by fozlerabbi321** [comment]
> getting this error on set
> 
> `android.bundle.enableUncompressedNativeLibs=false` in gradle.properties.
> 
> ```
> An exception occurred applying plugin request [id: 'com.android.application']
> > Failed to apply plugin 'com.android.internal.application'.
>    > com.android.builder.errors.EvalIssueException: The option 'android.bundle.enableUncompressedNativeLibs' is deprecated.
>      The current default is 'true'.
>      It was removed in version 8.1 of the Android Gradle plugin.
> ```



Your build is failing because of this line in your **`gradle.properties`**:

```properties
android.bundle.enableUncompressedNativeLibs=false
```

That property was **deprecated** and then **removed** in Android Gradle Plugin **8.1** — and your project is now using a version that no longer supports it.

---

### **How to fix**

Simply **remove** or **comment out** the line in `gradle.properties`:

```properties
# android.bundle.enableUncompressedNativeLibs=false
```

---

### **Why this works**

* In AGP 8.1+, uncompressed native libraries are already handled automatically when needed.
* Keeping the property causes the Gradle plugin to throw an error because it no longer recognizes it.

After removing it, run:
