### ISSUE TITLE
Error when android minsdkVersion is higher

### ISSUE THREAD

**Issue by SalohiddinSayfiddinov** [nizwar/openvpn_flutter#105]
Some packages in my app require minsdkVersion 23, but if i do so openvpn is throwing error "Error when show notification
E/de.blinkt.openvpn.core.OpenVPNService( 7358): android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{8e699e5 7358:com.haad.learn/u0a198} targetSDK=34" I i do not know what to do. Are there any solutions?

**Comment by Otajonov** [comment]
Hi Sir, Add these lines into your android/app/build.gradle file inside android {...}:

```

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }


```

**Comment by willieee802** [comment]
> Hi Sir, Add these lines into your android/app/build.gradle file inside android {...}:
> 
> ```
> 
>     packagingOptions {
>         jniLibs {
>             useLegacyPackaging = true
>         }
>     }
> ```

It doesn't seem to make a difference. It's still prompting that error every a few seconds

**Comment by Otajonov** [comment]
> > Hi Sir, Add these lines into your android/app/build.gradle file inside android {...}:
> > ```
> > 
> >     packagingOptions {
> >         jniLibs {
> >             useLegacyPackaging = true
> >         }
> >     }
> > ```
> 
> It doesn't seem to make a difference. It's still prompting that error every a few seconds

Hi there. Can you show the error output that is showing ? Maybe it is different problem in your case.

**Comment by willieee802** [comment]
> > > Hi Sir, Add these lines into your android/app/build.gradle file inside android {...}:
> > > ```
> > > 
> > >     packagingOptions {
> > >         jniLibs {
> > >             useLegacyPackaging = true
> > >         }
> > >     }
> > > ```
> > 
> > 
> > It doesn't seem to make a difference. It's still prompting that error every a few seconds
> 
> Hi there. Can you show the error output that is showing ? Maybe it is different problem in your case.

Hi, here's the error:

E/de.blinkt.openvpn.core.OpenVPNService(31590): Error when show notification
E/de.blinkt.openvpn.core.OpenVPNService(31590): android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1c3f148 31590:com.konnext.android.internal/u0a585} targetSDK=34
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.readParcelableInternal(Parcel.java:4900)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.readParcelable(Parcel.java:4882)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.createExceptionOrNull(Parcel.java:3082)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.createException(Parcel.java:3071)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.readException(Parcel.java:3054)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.os.Parcel.readException(Parcel.java:2996)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at android.app.Service.startForeground(Service.java:775)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVPNService.showNotification(OpenVPNService.java:361)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVPNService.updateByteCount(OpenVPNService.java:1264)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.VpnStatus.updateByteCount(VpnStatus.java:481)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVpnManagementThread.processByteCount(OpenVpnManagementThread.java:540)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:306)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:274) 
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at de.blinkt.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:218)
E/de.blinkt.openvpn.core.OpenVPNService(31590):         at java.lang.Thread.run(Thread.java:1012)

**Comment by nizwar** [comment]
This issue was solved with latest release
