### ISSUE TITLE
App Rejected from Google Play

### ISSUE THREAD

**Issue by Spokplacenta** [nizwar/openvpn_flutter#109]
Hello everyone, 
My app works well on IOS, as well as on Android. 
I published it as a test on the appStore and it was validated, however, on the Play Store, it's another story. I tried several configurations in the manifest, nothing to do, I always get rejected by Google with this answer:
<img width="751" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/f9804d70-2e13-4499-be0e-be23c892b8e1">

For those who posted, do you have this line in the AndroidManifest:
`﻿<uses-permission android:name="android.permission.BIND_VPN_SERVICE"/> `

I also filled out the form:
<img width="1191" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/addf37ee-ed24-4b03-9cd1-11955eeba7a2">

**Comment by minhbn00** [comment]
@Spokplacenta look like Google cannot find where your VPN feature is

**Comment by Spokplacenta** [comment]
> @Spokplacenta look like Google cannot find where your VPN feature is

Probably, is this coming from my way of implementing openvpn_flutter?
I ask for permission in "manifest - application", this may not be the right place.
I tried without asking permission but got the same error.

**Comment by minhbn00** [comment]
the "BIND_VPN_SERVICE" permission is needed for your app to run and start VPN service, and it is imported in the manifest file of the openvpn_flutter package.
So I think this is not a problem with the manifest or how you config it, maybe because Google can't test or can't find where your VPN feature is and then rejects your app

**Comment by Spokplacenta** [comment]
i solved my problem by explaining my use case by appeal. 🖖
