### ISSUE TITLE
MainActivity.java code but i use kotlin

### ISSUE THREAD

**Issue by bugrevealingbme** [nizwar/openvpn_flutter#11]
You shared this but my Flutter kotlin. What code do I need to put?

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        OpenVPNFlutterPlugin.connectWhileGranted(requestCode == 24 && resultCode == RESULT_OK);
        super.onActivityResult(requestCode, resultCode, data);
    }

**Comment by nizwar** [comment]
In kotlin, it will be like this
```kotlin
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        OpenVPNFlutterPlugin.connectWhileGranted(requestCode == 24 && resultCode == RESULT_OK)
        super.onActivityResult(requestCode, resultCode, data)
    }
```

Reopen the issue if you still has the problem, thankyou

**Comment by nizwar** [comment]
Almost forgot, don't forget to add this import, in case you add the code from vscode and not able to import it

```kotlin
import id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin
```

![Screen Shot 2022-02-22 at 15 36 42](https://user-images.githubusercontent.com/33113137/155093897-560e61bc-092a-4027-9111-79030799c2de.png)

**Comment by bugrevealingbme** [comment]
Cool, what about ios?

**Comment by bugrevealingbme** [comment]
My code knowledge is not enough, I don't understand. How to implement in Flutter?

**Comment by nizwar** [comment]
You can read instruction for iOS setup

**Comment by bihim** [comment]
Also dont forget to add this on your import section in MainActivity.kt
`import android.content.Intent`
