### ISSUE TITLE
ios 运行失败 错误如下

### ISSUE THREAD

**Issue by wangbf11** [nizwar/openvpn_flutter#113]
Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner' has copy command from '/Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/VPNExtension.appex' to '/Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex'
○ Target 'Runner'
○ Target 'Runner'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/VPNExtension.appex' to '/Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex'

Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.SwiftConstValuesFileList ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.SwiftConstValuesFileList ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files ->

node: <Copy /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/VPNExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-9E5487B43E84A5F4BC48AC01-Pods-Runner-resources-Debug-input-files-948d1cbbd3e019b428c68e56d84c86b1-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-9E5487B43E84A5F4BC48AC01-Pods-Runner-resources-Debug-input-files-948d1cbbd3e019b428c68e56d84c86b1-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-BBD8CE73416D8057A321F344-Pods-Runner-frameworks-Debug-input-files-097d554638d37855b44f20c40c87dcfb-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-BBD8CE73416D8057A321F344-Pods-Runner-frameworks-Debug-input-files-097d554638d37855b44f20c40c87dcfb-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/Info.plist ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/Info.plist /Users/woniu/Desktop/workspace/app-client/ios/Runner/Info.plist ->

node: /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/Runner.app/PlugIns/VPNExtension.appex /Users/woniu/Library/Developer/Xcode/DerivedData/Runner-clztsopvugfssxciljgjkvnjluhq/Build/Products/Debug-iphoneos/VPNExtension.appex

**Comment by almightyYantao** [comment]
我遇到了相同的问题，如何解决？
