### ISSUE TITLE
Connection problem on ios !

### ISSUE THREAD

**Issue by saeedpouryan** [nizwar/openvpn_flutter#119]
Hello
It works well on Android. But not in iOS

Stage is changing like below:
flutter: connecting
flutter: disconnected

My code:
`await engine.connect(Data.config, 'VPN', username: username, password: password, certIsRequired: true);`

I tested my config + username + password in other apps (OpenVpn) in iOS and it worked well
@nizwar

**Comment by saeedpouryan** [comment]
@nizwar

**Comment by nizwar** [comment]
Close this issue as duplicated #86
