### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel id.laskarmedia.openvpn_flutter/vpnstage)

### ISSUE THREAD

**Issue by sandoki** [nizwar/openvpn_flutter#14]
when I run the app I always have this error any posible solution?

**Comment by nizwar** [comment]
Hi, Make sure you run
“flutter pub get”

Stop and run your app again (only hot restart or got reload wont work).

**Comment by sandoki** [comment]
thanks nizwar I was now able to run on simulator but it can't connect on iOS simulator..

**Comment by sandoki** [comment]
I got this error any idea on this? 
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, Optional(Error Domain=NEVPNErrorDomain Code=5 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed}), IPC failed, null)

**Comment by nizwar** [comment]
Hi, Make sure you follow the instructions, if you encounter another error, open new issue with more detail how to produce it, thankyou

i'll close this issue :)

**Comment by ahmdsdk** [comment]
> I got this error any idea on this? [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, Optional(Error Domain=NEVPNErrorDomain Code=5 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed}), IPC failed, null)

I know it's been a while but for anyone facing this issue in the future; NetworkExtension cannot run on iOS simulator you have to use a real device. Check out this issue:
https://github.com/davlxd/NEPacketTunnelVPNDemo/issues/1
