### ISSUE TITLE
Execution failed for task ':openvpn_flutter:verifyReleaseResources'.

### ISSUE THREAD

**Issue by cyzlucky** [nizwar/openvpn_flutter#15]
* What went wrong:
Execution failed for task ':openvpn_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\cyz\.gradle\caches\transforms-3\85a4b6c8bc3231eaaf425d8692a95516\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by cyzlucky** [comment]
environment:
  sdk: ">=2.17.0-125.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  openvpn_flutter: ^1.1.3

**Comment by 0ttik** [comment]
Same issue for me when trying to build for a project with kotiln.

**Comment by 0ttik** [comment]
I think I found the solution. It is essentially a workaround, but it works. See here: https://github.com/nizwar/openvpn_flutter#publishing-to-play-store-and-app-store. 

You should build appbunlde instead of apk.
