### ISSUE TITLE
iOS, Not connecting with VPN server

### ISSUE THREAD

**Issue by GreenPixi** [nizwar/openvpn_flutter#2]
After starting connection the status shows **VPNStage.unknown** but when i check on iOS device Settings->VPN->Status it shows connecting, I waited for long time but does not connect.

Thank You guys.

**Comment by KamalPixi** [comment]
Any solution guys?

**Comment by nizwar** [comment]
I'm sorry, I missed something while push the plugin, i'll update it soon

**Comment by nizwar** [comment]
Hi, i just update the plugin, you might need to check it again and follow the instructions.

Let me know if you still face the problems and don't forget to close it solved :)
