### ISSUE TITLE
Intl Dependency Issue

### ISSUE THREAD

**Issue by aQuillaSense** [nizwar/openvpn_flutter#20]
Hi,

When I add the package to my pubspec.yaml and it gets the packages I get an error as follows:

`Because every version of flutter_openvpn depends on intl ^0.16.1 and glorifi_wifi depends on intl ^0.17.0, flutter_openvpn is forbidden`

My application is dependent on intl ^0.17.0

**Comment by nizwar** [comment]
Hi, it seems like you open issue in wrong package,
you might need to open issue on flutter_openvpn (https://gitlab.com/topfreelancerdeveloper/flutter_openvpn) instead, because it is openvpn_flutter and doesn't use intl
