### ISSUE TITLE
Question: removing disconnect button from notifications

### ISSUE THREAD

**Issue by repfly** [nizwar/openvpn_flutter#23]
Hello,

I've been trying to remove the disconnect button and modify the information displayed on notification bar in android when the vpn is connecting. Any idea for how to proceed? I've tried importing the package internally by copying from pub cache then editing it. But changes did not made any effect on the build.

**Comment by Thebubeev** [comment]
have you found the solution?

**Comment by Thebubeev** [comment]
> > have you found the solution?
> 
> @Thebubeev hello, yes. I forked the Android VPN library and removed the related notification. Then referenced it in a customized library that being held locally in Flutter project.

hello, thanks for your answer. 
did you fork initially this library https://github.com/schwabe/ics-openvpn?
