### ISSUE TITLE
> Hi guys, this issue will be solved on next publish openvpn_flutter 1.2.0, i will close it for now and feel free to reopen if the issue still exists

### ISSUE THREAD

**Issue by moumen14dz** [nizwar/openvpn_flutter#24]
> Hi guys, this issue will be solved on next publish openvpn_flutter 1.2.0, i will close it for now and feel free to reopen if the issue still exists

hello, thanks 
it worked in iphone from xcode but in ios testfly and published ios app not work  byteIn and byteOut

_Originally posted by @moumen14dz in https://github.com/nizwar/openvpn_flutter/issues/6#issuecomment-1153314233_

**Comment by nizwar** [comment]
Oh, i think i forgot to mention you've to update your PacketTunnelProvider.swift with the [new one](https://raw.githubusercontent.com/nizwar/openvpn_flutter/master/example/ios/VPNExtension/PacketTunnelProvider.swift)

Let me know if its work or not

**Comment by nizwar** [comment]
I'll close this issue, feel free to open it again if it doesn't work

**Comment by moumen14dz** [comment]
hello, i updated PacketTunnelProvider.swift but same 
it worked in iphone from xcode but in ios testfly and published ios app not work byteIn and byteOut
