### ISSUE TITLE
Connection time tracking when app is terminated

### ISSUE THREAD

**Issue by 0ttik** [nizwar/openvpn_flutter#29]
Following #12 issue. If we exit and re-enter app we could use `OpenVPN#isConnected` method. But how do I keep track of the time VPN is being connected? 

For now I can only think about making some kind of foreground service tracking time for which app is being connected. Are there any way to get this info from VPN state from OS itself?

**Comment by NilupulTreinetic** [comment]
@nizwar onVpnStatusChanged: not given any data when the app is terminated and reopened on the iOS.Is there any way to get this?

**Comment by NilupulTreinetic** [comment]
@0ttik  did you able to fix that issue? any luck

**Comment by 0ttik** [comment]
> @0ttik did you able to fix that issue? any luck

I'm just using shared_preferences to store connection start timestamp and then calculate connection duration.

**Comment by iamadeeb** [comment]
Is there any update on this issue?
