### ISSUE TITLE
i cant fix this Bugs 

### ISSUE THREAD

**Issue by MAFIACHEATS** [nizwar/openvpn_flutter#30]
![WhatsApp Image 2022-07-06 at 03 56 29](https://user-images.githubusercontent.com/107152859/177538739-f9b23e71-f0bf-4804-b153-c0b7bc8d9994.jpeg)
the bug is the Connection status shows like that VPNStage.connected but the right one will shows connected only not VPNStage.connected

also the same for  duration is show {:00:00:20} but the right one will show 00:00:20 only

so anyone can fix this please

**Comment by nizwar** [comment]
It was logical things, you can catch the result by doing 
```dart
var label = "Unknown";
switch(vpnStage){
  case VPNStage.connected:
      label = "Connected";
     break
}
/// ....
/// and simply render it
... Text(label)
/// ....
}
```
if you 'lazy' enough, on flutter 3 you can show enum value by doing this
```dart
vpnstage.name
```

some refference https://medium.com/codex/flutter-3-what-are-enums-and-what-is-new-about-it-f5f2c481e7b5
