### ISSUE TITLE
iOS Connection error

### ISSUE THREAD

**Issue by muratmjdci** [nizwar/openvpn_flutter#32]
Hello, when I try to connect vpn, iOS tries to connect but fails immediately, and this is what I see in my terminal;

[]  Failed to save configuration Localized Description: Error Domain=NEConfigurationErrorDomain Code=5 "configuration is stale" UserInfo={NSLocalizedDescription=configuration is stale}
[] Failed to save configuration: Error Domain=NEVPNErrorDomain Code=4 "configuration is stale" UserInfo={NSLocalizedDescription=configuration is stale}
[]  Failed to save configuration Localized Description: Error Domain=NEConfigurationErrorDomain Code=5 "configuration is stale" UserInfo={NSLocalizedDescription=configuration is stale}

**Comment by zikwall** [comment]
Please tell us how you solved this problem?

**Comment by muratmjdci** [comment]
Well it's been a year, I have solved it after 3-5 days of struggling for now I have no idea what problem is and how I solved
