### ISSUE TITLE
Cannot connect on ios.

### ISSUE THREAD

**Issue by ismailcaakir** [nizwar/openvpn_flutter#39]
Hi,

Thank you very much for the development. It works pretty well on Android, but I can't connect on iOS. It quickly switches to Connecting -> Disconnecting. I've tested my VPN file on every platform and it works fine on all of them. I applied your configuration settings step by step.

Can anyone run this code on ios? Telegram: @ismailcaakir

**Comment by 0ttik** [comment]
Most likely dub of https://github.com/nizwar/openvpn_flutter/issues/9.

**Comment by ismailcaakir** [comment]
I used this code block. I couldn't connect.

I tried the main.dart file you created exactly.

` engine.connect(config, "USA", username: defaultVpnUsername, password: defaultVpnPassword, certIsRequired: true);`

**Comment by 0ttik** [comment]
Ok, then there is some other issue most likely. I don't know how to help you there.

**Comment by ismailcaakir** [comment]
were you able to connect to both ios and android? This answer will be enough for me.

**Comment by 0ttik** [comment]
> were you able to connect to both ios and android? This answer will be enough for me.

After suggested change I'm able to connect on both iOS and Android.

**Comment by nizwar** [comment]
You might need to check your OpenVPN config, check it with OpenVPN client software
