### ISSUE TITLE
Could not resolve com.github.nizwar:openvpn_library:20455163ea.

### ISSUE THREAD

**Issue by ferdigokdemir** [nizwar/openvpn_flutter#4]
Version: openvpn_flutter: ^1.1.2
<img width="1043" alt="Screen Shot 2022-01-17 at 16 40 09" src="https://user-images.githubusercontent.com/23097465/149779229-39e130e6-5a9e-4f68-8c53-696dac613fc5.png">

**Comment by nizwar** [comment]
Hi, can you use VPN or different network while doing so? let me know the result

**Comment by ferdigokdemir** [comment]
I didn't understand but now working :D . I did nothing.

**Comment by nizwar** [comment]
😊 Great news, i'll close the issue now, feel free to open it again if you encounter same problem
