### ISSUE TITLE
Cannot connect on android

### ISSUE THREAD

**Issue by hhacker1999** [nizwar/openvpn_flutter#40]
W/System.err(16211): android.os.RemoteException: You must select a User certificate
W/System.err(16211): 	at de.blinkt.openvpn.OpenVpnApi.startVpnInternal(OpenVpnApi.java:36)
W/System.err(16211): 	at de.blinkt.openvpn.OpenVpnApi.startVpn(OpenVpnApi.java:26)
W/System.err(16211): 	at de.blinkt.openvpn.VPNHelper.connect(VPNHelper.java:87)
W/System.err(16211): 	at de.blinkt.openvpn.VPNHelper.startVPN(VPNHelper.java:54)
W/System.err(16211): 	at de.blinkt.openvpn.VPNHelper.startVPN(VPNHelper.java:69)
W/System.err(16211): 	at id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin.lambda$onAttachedToEngine$0$OpenVPNFlutterPlugin(OpenVPNFlutterPlugin.java:124)
W/System.err(16211): 	at id.laskarmedia.openvpn_flutter.-$$Lambda$OpenVPNFlutterPlugin$MYzEvF67BUjl9cSM6FJLspBJmSI.onMethodCall(Unknown Source:2)
W/System.err(16211): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(16211): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(16211): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(16211): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(16211): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(16211): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(16211): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(16211): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(16211): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16211): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(16211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Same config works on other clients

**Comment by ismailcaakir** [comment]
Did it work on iOS devices?

**Comment by nizwar** [comment]
I've answer this on #63 (with relevant question)
