### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by shafiquecbl** [nizwar/openvpn_flutter#46]
I created new Flutter project with flutter version 3.3 and according to your documentation i added below line in "MainActivity.java" and it shows error when i run the app.  I doesn’t recognize the below line and its import

 OpenVPNFlutterPlugin.connectWhileGranted(requestCode == 24 && resultCode == RESULT_OK)

**Comment by macopi** [comment]
Im trying to make this work, i will help you with this bug.

```
package com.ablstream
import io.flutter.embedding.android.FlutterActivity
import android.content.Intent
import id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin
class MainActivity: FlutterActivity() {

    // onActivityResult
    override protected fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        OpenVPNFlutterPlugin.connectWhileGranted(requestCode == 24 && resultCode == RESULT_OK);
        super.onActivityResult(requestCode, resultCode, data)
    }
}
```

**Comment by nizwar** [comment]
Hi, i'm sorry to not mentioned the import, i've update the docs with @0ttik pull request
import id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin;
