### ISSUE TITLE
Cannot start a VPN connection

### ISSUE THREAD

**Issue by macopi** [nizwar/openvpn_flutter#48]
Hi there im having problems starting a vpn with your plugin, in Android.

i follow your instructions in README for install, but when i try to connect i'm always getting this:

```
I/flutter (28647): noprocess
I/flutter (28647): vpn_generate_config
I/OpenVPN (28647): Starting openvpn
I/OpenVPN (28647): /data/app/~~RnAQ1vWiar8pyOj9IzVFOw==/com.ablstream-QT730sYeK4D11Aqyno6Alw==/lib/x86_64:/data/app/~~RnAQ1vWiar8pyOj9IzVFOw==/com.ablstream-QT730sYeK4D11Aqyno6Alw==/lib/x86_64/libovpnexec.so
I/OpenVPN (28647): OpenVPN process exited
I/flutter (28647): noprocess
I/OpenVPN (28647): Exiting
I/flutter (28647): disconnected
```

Can anyone help to fix this ?
thanks in advance.

**Comment by macopi** [comment]
I found the solution: you should run MIN SDK 21. That will fix the problem... Maybe looking for fix this in next commit !! :)

**Comment by nizwar** [comment]
Hi, glad you discovered the issues and shared it here

**Comment by canibal1** [comment]
I have same issue @nizwar  please help me? I did minsdkversion 21 
also I did this config: 
gradle.properties > android.bundle.enableUncompressedNativeLibs=false
AndroidManifest > android:extractNativeLibs="true" in application tag

Please help me, if I cannot find any solution, my boss will fire to me :(
