### ISSUE TITLE
Can't build release apk or aab

### ISSUE THREAD

**Issue by 92sajid110** [nizwar/openvpn_flutter#49]
Error
* What went wrong:
Execution failed for task ':openvpn_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\pc\.gradle\caches\transforms-3\eec8bc517f1e84f6510d068356dfdca3\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
     

Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19044.2130], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.72.2)
[√] Connected device (1 available)
[√] HTTP Host Availability
• No issues found!

compileSdkVersion 31
minSdkVersion 22
targetSdkVersion 31
 multiDexEnabled true
ext.kotlin_version = '1.6.0'
classpath 'com.android.tools.build:gradle:7.1.2'

also added from google search about resource android:attr/lStar not found.
configurations.all {
    resolutionStrategy {
        force 'androidx.core:core-ktx:1.6.0'
    }
}

**Comment by 92sajid110** [comment]
ANY HELP

**Comment by mzulfaas** [comment]
Is already solved ?

**Comment by 92sajid110** [comment]
Not yet.
I checked it is not building apk or aab

**Comment by 92sajid110** [comment]
> Is already solved ?

Can you share how did you solved

**Comment by 92sajid110** [comment]
Error: android:exported needs to be explicitly specified for element <service#de.blinkt.openvpn.api.ExternalOpenVPNService>. Apps targeting Android 12 and higher are required 
to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by Thebubeev** [comment]
same issue

**Comment by mzulfaas** [comment]
type this in your terminal flutter build apk --debug

**Comment by mzulfaas** [comment]
or flutter build appbundle

**Comment by 92sajid110** [comment]
> same issue

Which one first i mentioned android lstar missing or android:exported missing

Did anyone have fixed this i googled some stuffs and added android: exported in manifest of package but not work

**Comment by 92sajid110** [comment]
> type this in your terminal flutter build apk --debug

Did you know fix

**Comment by nizwar** [comment]
Hi, can you tell me what is your flutter version?
and can you build apk with the example project?

**Comment by 92sajid110** [comment]
> AAPT: error: resource android:attr/lStar not found.

debug apk builds

**Comment by 92sajid110** [comment]
> Can you build apk with the example project?

Yes

**Comment by 92sajid110** [comment]
yes sir

**Comment by nizwar** [comment]
I mean clone the [example project](https://github.com/nizwar/openvpn_flutter/tree/master/example), and run `flutter build apk` or `flutter build appbundle`

**Comment by 92sajid110** [comment]
After adding some plugins in your example it throws warning
Warning: The plugin url_launcher_android requires Android SDK version 33.
Please update to Android 33

**Comment by nizwar** [comment]
You can change it on build.gradle

**Comment by 92sajid110** [comment]
Ok find it but my project not works

**Comment by 92sajid110** [comment]
flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  auto_size_text: ^3.0.0
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  country_icons: ^2.0.2
  provider: ^6.0.4
  url_launcher: ^6.1.6
  lottie: ^1.4.3
  
  Flutter Sdk 3.3.3

**Comment by nizwar** [comment]
Since the issues going so wild and didn't focus at one topic, i'm afraid i need to close it... kindly seperate it on different topic so i can check it one by one

**Comment by mzulfaas** [comment]
PS C:\Users\mz002\StudioProjects\anonvacy_app> flutter build apk --split-per-abi

 Building with sound null safety 

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sodium-0.2.0\android\src\main\java\com\firstfloorsoftware\flutter_sodium\FlutterSodiumPlugin
.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter_android-2.3.3\android\src\main\java\io\flutter\plugins\googlemaps\Convert.java u
ses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-std
lib-jdk8-1.5.30.jar (version 1.5)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.21/568c1b78a8e17a4f35b31f0a74e2916095ed74c2/kotlin-std
lib-jdk7-1.6.21.jar (version 1.6)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1
.6.21.jar (version 1.6)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-s
tdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-std
lib-jdk8-1.5.30.jar (version 1.5)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.21/568c1b78a8e17a4f35b31f0a74e2916095ed74c2/kotlin-std
lib-jdk7-1.6.21.jar (version 1.6)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1
.6.21.jar (version 1.6)
    C:/Users/mz002/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-s
tdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
FAILURE: Build failed with an exception.

* What went wrong:

> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\mz002\.gradle\caches\transforms-3\cf794fe5d5a8f5f0d65e116ba31d8131\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT:
error: resource android:attr/lStar not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 44s
Running Gradle task 'assembleRelease'...                          225.9s
Gradle task assembleRelease failed with exit code 1


I have same issue here

**Comment by mzulfaas** [comment]
Cannot build apk release or flutter build apk --split-per-abi
