### ISSUE TITLE
How can i show permission dialog?

### ISSUE THREAD

**Issue by ferdigokdemir** [nizwar/openvpn_flutter#5]
Vpn permission dialog show when connect vpn.
I want show this dialog when initialize or custom function.

**Comment by nizwar** [comment]
Hi, this feature is available now, update your openvpn_flutter to 1.1.3, you can show permission request by calling _engine.requestPermissionAndroid()

if you still have related issue, feel free to reopen the issue

**Comment by ferdigokdemir** [comment]
Can you add this code for kotlin version?

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        OpenVPNFlutterPlugin.connectWhileGranted(requestCode == 24 && resultCode == RESULT_OK);
        super.onActivityResult(requestCode, resultCode, data);
    }

**Comment by nizwar** [comment]
Take a look at this issue #11, thankyou
