### ISSUE TITLE
Google Console Crash : defective version of the OpenSSL library

### ISSUE THREAD

**Issue by taimoor522** [nizwar/openvpn_flutter#52]
Defective libraries
help_outline
Defective OpenSSL Version
error
Error
brightness_1
Issue 1 of 1
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:

OpenSSL 1.1.1g in lib/x86_64/libopenvpn.so

**Comment by memishood** [comment]
same problem here

**Comment by nizwar** [comment]
I've Updated [libopenvpn.so](https://github.com/nizwar/openvpn_library/commit/b18b1c5eb099d11d02c67ee0f2eb2feda659858a) and this issue must be solved, its available on openvpn_flutter 1.2.1

if it still happened feel free to open it
