### ISSUE TITLE
Android cannot be used, 'config' has been configured, the log information is as follows

### ISSUE THREAD

**Issue by szxv587** [nizwar/openvpn_flutter#57]
Debug service listening on ws://127.0.0.1:56391/N9eNUUdVzyU=/ws
Syncing files to device Mi 10 Pro...
D/openvpn (13181): Loading openvpn native library $id$ compiled on Jun 23 2020 13:36:40
D/DecorView[](13181): onWindowFocusChanged hasWindowFocus true
D/CompatibilityChangeReporter(13181): Compat change id reported: 160794467; UID 11067; state: ENABLED
I/OpenVPN (13181): Starting openvpn
I/OpenVPN (13181): /data/app/~~OlyiEBvzZplm_o9kvHTqBw==/id.laskarmedia.openvpn_flutter_example-ZAqJy4oLonkEiUj1Ag0xOw==/lib/arm64:/data/app/~~OlyiEBvzZplm_o9kvHTqBw==/id.laskarmedia.openvpn_flutter_example-ZAqJy4oLonkEiUj1Ag0xOw==/lib/arm64/libovpnexec.so
I/OpenVPN (13181): OpenVPN process exited
I/OpenVPN (13181): Exiting

**Comment by kashiflab** [comment]
I am also facing the same issue can you please tell me how you fix it?
