### ISSUE TITLE
Test demo ios compilation failed

### ISSUE THREAD

**Issue by dollarkillerx** [nizwar/openvpn_flutter#58]
code:  github.com/nizwar/openvpn_flutter/tree/master/example

### basic information
flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (2 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

OS: macOS Monterey12.6.1 M1

Xcode12.0

### error message
```
openvpn_flutter/example/ios/Pods/Target Support Files/Pods-VPNExtension/Pods-VPNExtension.debug.xcconfig

Target Support Files/Pods-VPNExtension/Pods-VPNExtension.debug.xcconfig:1:1 unable to open configuration settings file

Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-input-files.xcfilelist'
```

![](https://i.imgur.com/4FbmFOp.jpg)

![](https://i.imgur.com/s00zgXI.jpg)

![](https://i.imgur.com/wzLrJZE.jpg)

**Comment by mzulfaas** [comment]
any update?

**Comment by nizwar** [comment]
This error indicates team id still attached with mine, you have to select your own team id, or in some cases change the bundle identifier also, 

if you using xcode 14, try this solution https://stackoverflow.com/questions/73711671/flutter-ios-build-error-select-a-development-team-in-the-signing-capabiliti
