### ISSUE TITLE
ios issues (byteIn and byteOut not updated every status change)

### ISSUE THREAD

**Issue by moumen14dz** [nizwar/openvpn_flutter#6]
if (Platform.isIOS) {
          var splitted = data.split("_");
          var connectedOn = DateTime.tryParse(splitted[0]);
          if (connectedOn == null) {
            return onVpnStatusChanged?.call(VpnStatus.empty());
          }

          onVpnStatusChanged?.call(VpnStatus(
            duration: _duration(DateTime.now().difference(connectedOn).abs()),
            byteIn: splitted[2],
            byteOut: splitted[3],
            lastPacketReceive: splitted[1],
          ));
        } else {

lastPacketReceive  , byteIn , byteOut not updated in ios version 

also vpn not connect in ios version under 15

**Comment by KamalPixi** [comment]
It works on iOS, iPad 9.0 - 15.3

**Comment by moumen14dz** [comment]
But our app worked in ios 15 and in ios 14 not connecting to VPN , do you
have any idea
Thanks

**Comment by KamalPixi** [comment]
With this library apple rejected the app. apple said "VPN does not connect on iPad 15.3" but when I check with iPad 15.3 it works fine. now i'm not sure what to do.

for iOS 14 i'm not sure. I did not test on that.

Just a note.
If u design ur app only for iPhone but still ur app need to work with iPad as well -by Apple

**Comment by Nathan9745354** [comment]
> With this library apple rejected the app. apple said "VPN does not connect on iPad 15.3" but when I check with iPad 15.3 it works fine. now i'm not sure what to do.
> 
> for iOS 14 i'm not sure. I did not test on that.
> 
> Just a note. If u design ur app only for iPhone but still ur app need to work with iPad as well -by Apple

Hi KamalPixi , 

We passed the apple reviews on Ipad/Iphone 15.2/3 I not sure .2 or .3 , but final it's worked on IOS15 anyway.
Well , this library have 0.2.0 , it's work for 14 under , but not work on IOS 15.x , if apple rejected you that mean it's really didn't worked at 15.3 , you should try it on TestFlight , because features not work fine on production mode (TestFlight) but working on Xcode or Debug mode. Another thing you should try IOS14 or under this version for test your app.

**Comment by KamalPixi** [comment]
When I test on TestFlight and It works fine on iPhone/iPad 15.3

May we work together to pass it Apple review?
I have iPhone 6, iPhone 12,13 and iPad mini 5th Gen.

My what'sapp +601111085061
Thank You

**Comment by nizwar** [comment]
I've look at this issues and be able to produce it, i still looking for solutions...

Also any PRs that related with this issues are needed

**Comment by Nathan9745354** [comment]
> I've look at this issues and be able to produce it, i still looking for solutions...
> 
> 
> 
> Also any PRs that related with this issues are needed 

Hi ,

Any update?
Thanks

**Comment by moumen14dz** [comment]
> It works on iOS, iPad 9.0 - 15.3

did you test it, because for me vpn not connecter in ios under 15

**Comment by gyspy** [comment]
Hi,
Any updates?
On android it works like a charm, but on iOS it stops just after the trying to connect.

How can I turn on native library (or adapter, don't know what exactly is in use) logs to see what is happening in background? Sorry, for this question, 'cause I am not familiar with iOS development and trying to fix the plugin just by examine the sources and comparing 'em to another projects.

**Comment by bugrevealingbme** [comment]
Same here

**Comment by xsid86** [comment]
@nizwar,

Well, finally It is working.
Be sure that openvpn config has \n at the end of the file (or string, in case you retrieve it via network) and remove

`if (!certIsRequired) config += "client-cert-not-required";`

in `lib/src/vpn_engine.dart` in the flutter plugin

not sure if this is enough, 'cause there were some changes in capabilities. Tell me if you. need a full list of caps enabled (only in case if all above not working)

------

PS: NEED TO BE TESTED ON ANDROID AFTER ALL OF THIS.

**Comment by memishood** [comment]
Same here

**Comment by nizwar** [comment]
Hi guys, this issue will be solved on next publish openvpn_flutter 1.2.0, i will close it for now and feel free to reopen if the issue still exists

**Comment by moumen14dz** [comment]
> Hi guys, this issue will be solved on next publish openvpn_flutter 1.2.0, i will close it for now and feel free to reopen if the issue still exists

hello, thanks 
it worked in iphone from xcode but in ios testfly and published ios app not work  byteIn and byteOut
