### ISSUE TITLE
not connecting on android

### ISSUE THREAD

**Issue by Adil-Ashfaq35** [nizwar/openvpn_flutter#60]
I/flutter (28647): noprocess
I/flutter (28647): vpn_generate_config
I/OpenVPN (28647): Starting openvpn
I/OpenVPN (28647): /data/app/~~RnAQ1vWiar8pyOj9IzVFOw==/com.ablstream-QT730sYeK4D11Aqyno6Alw==/lib/x86_64:/data/app/~~RnAQ1vWiar8pyOj9IzVFOw==/com.ablstream-QT730sYeK4D11Aqyno6Alw==/lib/x86_64/libovpnexec.so
I/OpenVPN (28647): OpenVPN process exited
I/flutter (28647): noprocess
I/OpenVPN (28647): Exiting
I/flutter (28647): disconnected

**Comment by sajjatflutterdeveloper** [comment]
same issue bro  you have any solution

**Comment by nizwar** [comment]
Have you try connect your config with openvpn client app?

**Comment by sajjatflutterdeveloper** [comment]
yes bro now I am trying to implement tunnelKit native Library
