### ISSUE TITLE
Unable to connect on iOS 15.7.1 and lower with "Update Required" in VPN Configuration

### ISSUE THREAD

**Issue by ahmdsdk** [nizwar/openvpn_flutter#61]
Hello, I am facing an issue while running on iOS 15.7.1 and lower while it works fine on 16.1.1 and 16.1.2. My project's deployment target is 11.0 both in Podfile and in Runner Target general. With iPhone 7 iOS 15.7.1 and iPhone 6 iOS 12.5.6 VPN cannot connect and I get "Update Required" in the VPN Configuration in the iPhone settings. @nizwar can someone help me with this issue?

**Comment by ahmdsdk** [comment]
Solved by changine VPNExtension Target > Build Settings > Changing iOS deployment target to 11.0 and then Editing the code in PacketTunnelProvider file on line 144 from
`
UserDefaults.init(suiteName: groupIdentifier)?.setValue(formatter.string(from: Date.now), forKey: "connected_on")
`
to
`
UserDefaults.init(suiteName: groupIdentifier)?.setValue(formatter.string(from: Date()), forKey: "connected_on")
`

**Comment by Oshaine** [comment]
This does not on IOS, i am still getting Update Required

**Comment by syedabdulbasit1** [comment]
@ahmdsdk any changes on PacketTunnelProvider file does not effect because it is not calling anywhere
