### ISSUE TITLE
How To Add Config File ? Please Help Me. 

### ISSUE THREAD

**Issue by rahat14** [nizwar/openvpn_flutter#62]
Future<void> initPlatformState() async {
    engine.connect(config, "USA",
        username: defaultVpnUsername,
        password: defaultVpnPassword,
        certIsRequired: false);
    if (!mounted) return;
  }

what to pass in config here , path to the config file or the whole file content. both of them tried did not work.

**Comment by nizwar** [comment]
You have to fill it with openvpn config script (file content)

**Comment by rahat14** [comment]
it showing me an error can u help me by giving an example?  I am adding a configuration file. [https://we.tl/t-45CzR7wXCr](url)

**Comment by nizwar** [comment]
Example
https://github.com/nizwar/openvpn_flutter/blob/5c9567efbf0d4c7efcce14746d1cfa3fb287db28/example/lib/main.dart

**Comment by rahat14** [comment]
@nizwar  thnx man. but now it is stuck on VPNStage.unknown . but the same file is running on OpenVPN  windows client perfectly

**Comment by kashiflab** [comment]
@nizwar Please have a look into this error "stuck on VPNStage.unknown"

**Comment by mekkolodziejski** [comment]
Future<FileModel> _readFileFromAssets() async {
    final data = await rootBundle.loadString(_files[sharedPreferences.getInt('position')!]);
    List<String> lines = data.split('\n');
    StringBuffer sb = StringBuffer();
    String ip = '';
    int x = 0;
    for (var line in lines) {
      if (line.contains('remote ')) {
        ip = line.split(' ')[1];
      }
      if (x == 5) {
        sb.writeln('data-ciphers AES-128-CBC');
        sb.writeln('data-ciphers-fallback AES-128-CBC');
      }
      sb.writeln(line);
      x++;
    }
    FileModel fm = FileModel(config: sb.toString(), ip: ip);
    return fm;
  }

**Comment by mekkolodziejski** [comment]
Future<FileModel> _readFileFromAssets() async {
    final data = await rootBundle.loadString(_files[sharedPreferences.getInt('position')!]);
    List<String> lines = data.split('\n');
    StringBuffer sb = StringBuffer();
    String ip = '';
    int x = 0;
    for (var line in lines) {
      if (line.contains('remote ')) {
        ip = line.split(' ')[1];
      }
      sb.writeln(line);
      x++;
    }
    FileModel fm = FileModel(config: sb.toString(), ip: ip);
    return fm;
  }
