### ISSUE TITLE
User certificate error

### ISSUE THREAD

**Issue by andreacocci95** [nizwar/openvpn_flutter#63]
Hi, I tried to implement your package on my project for connecting to a VPN of my shurshark account.

I downloaded from website the ovpn file and copied all the content inside the config. I also added username and password provided from surfshark and set certIsRequired true.

When I try to start the VPN, I receive an error on debug console that say: You must select a user certificate (or something similar).

What I'm doing wrong?

**Comment by nizwar** [comment]
as the error mentioned, you need to put openvpn's certificate inside your openvpn script, you can check vpngate or any public free openvpn servers, 

i'll close this issue as it is openvpn script related, not the plugin :)

**Comment by andreacocci95** [comment]
For how have the same problem: I retrieve this problem copying my ovpn config content and tired to make it inline string. When I added my ovpn on assets and read the file everything works.
