### ISSUE TITLE
Parallel Connecting Issue

### ISSUE THREAD

**Issue by Nyan-Win-Naing** [nizwar/openvpn_flutter#65]
Hello my friends! I have written codes like the example which is showing in pub.dev docs. But I have some issues, let me explain it. When testing,  I connected VPN with my phone first and my mom connected after me. After my mom connected, both VPNs from two phones are disconnected and connected again and again. Why ??

**Comment by nizwar** [comment]
You might need to check your server, it is not client related, in this plugin there is no function  to disconnect another user's connection
