### ISSUE TITLE
After the connection permission

### ISSUE THREAD

**Issue by bugrevealingbme** [nizwar/openvpn_flutter#8]
After the connection permission, it is necessary to press the reconnect button. This shouldn't happen. It should connect after giving permission.

<img width="393" alt="Ekran Resmi 2022-02-17 11 14 26" src="https://user-images.githubusercontent.com/22865739/154433521-8dd86e49-fb26-4701-9359-84a1d8805bc3.png">

**Comment by moumen14dz** [comment]
you can request permtioj just after app started

**Comment by bugrevealingbme** [comment]
I allow, no reaction after allow. It's just like that in the PlayStore
version. No problem on release apk or debug

moumen14dz ***@***.***>, 18 Şub 2022 Cum, 21:15 tarihinde
şunu yazdı:

**Comment by bugrevealingbme** [comment]
> you can request permtioj just after app started

But it makes more sense to automatically connect after the trace. I want this

**Comment by nizwar** [comment]
Hi, this feature is available now, update your openvpn_flutter to 1.1.3, if you still have related issue, feel free to reopen the issue
