### ISSUE TITLE
Android OK - IOS KO

### ISSUE THREAD

**Issue by Spokplacenta** [nizwar/openvpn_flutter#86]
When I try connection on Android, it's working.
When I try on my iPad or iPhone, it's not working. 
I didn't find any way to handle errors, I've just status and stage : 
`flutter: status : {connected_on: null, duration: 00:00:00, byte_in: 0, byte_out: 0, packets_in: 0, packets_out: 0}
flutter: stage : VPNStage.disconnected
flutter: stage : VPNStage.connecting
flutter: stage : VPNStage.disconnected`

In VPN configuration in iPadOS or iOS, i have :
"Update required"  in vpn's list 

What is the way to handle errors ?

OpenVPNAdapter is no longer maintained, is it planned to use tunnel kit instead of openVPNAdapter ?

**Comment by syedabdulbasit1** [comment]
@Spokplacenta Did you find anything because I got the same issue

**Comment by Spokplacenta** [comment]
Still same problem on Apple's platforms. 
Did you get any error messages ?

**Comment by syedabdulbasit1** [comment]
I configure it correctly but don't get it where the issue is coming from

**Comment by Spokplacenta** [comment]
Does your configuration work on android ?

**Comment by syedabdulbasit1** [comment]
@Spokplacenta yes it works on android and IOS also
You just need to configure VPNExtension build deployment target 15.0.0 and it's working

**Comment by Spokplacenta** [comment]
Yes, minimum Deployments is on iOS 15.0 everywhere
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/6cd73544-cb3a-486c-8cac-34c555d1f23b)
My problem is when I launch app, I have popup to allow VPN connexion and no connect :

on the VPN list on iPad I have on "**AppName - Update required**"
<img width="850" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/4ae5b899-e100-4950-b3a4-4cc9598eb319">

**Comment by syedabdulbasit1** [comment]
@Spokplacenta check your ios OS software version if it is equal to or greater than 15 than it will work,
Also add Personal VPN Extension in both Runner and VPNExtension.
Sorry for late reply because I was not feeling well due to flu and fever.
![Screenshot 2023-10-23 at 10 46 16 AM](https://github.com/nizwar/openvpn_flutter/assets/107464389/f7969984-0456-4873-b67f-45ee36de6d22)

**Comment by Spokplacenta** [comment]
Still same problem
Runner : 
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/d77d56f5-8517-446d-832f-d912f031d6cd)
VPNExtension
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/2d7396ce-c6bf-4a1a-a139-a89fbf8d571d)

**Comment by syedabdulbasit1** [comment]
Run below command and run again
flutter clean && flutter pub get && pod deintegrate && pod install
Could you tell me about the Software version of your iPhone?

**Comment by Spokplacenta** [comment]
iPad version 17.0.3

![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/dd65d9e8-5903-4205-b63c-cb3c36c0ca89)

PodFile : 
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/70f3ac5d-b69d-4c45-b65f-8eeb495a60e1)

**Comment by syedabdulbasit1** [comment]
Add below in runner Info.plist that might help you
 
    <key>BGTaskSchedulerPermittedIdentifiers</key>
    <array>
       <string>workmanager.background.task</string>
    </array>
	<key>NSBonjourServices</key>
    <array>
        <string>_dartobservatory._tcp</string>
    </array>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>

**Comment by syedabdulbasit1** [comment]
Have you added code on PacketTunnelProvider.swift?

**Comment by Spokplacenta** [comment]
yes like this :
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/2332c2ed-c84f-45d9-a666-ebe3459b2ce7)

**Comment by syedabdulbasit1** [comment]
yes

**Comment by syedabdulbasit1** [comment]
make a separate project and start the installation step by step, I know it will take time maximum 20 minutes but you will find the issue may be.

**Comment by Spokplacenta** [comment]
How is set your libraries in runner ? 
Runner : 
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/794531b7-fad1-4ea2-ac9d-2e092d6433c8)
VPNExtension 
![image](https://github.com/nizwar/openvpn_flutter/assets/71837821/80e9d61e-cfe2-4a2e-bdfd-ee27e0f4e716)

On the test, by default I have this but I have a loop...

**Comment by syedabdulbasit1** [comment]
![image](https://github.com/nizwar/openvpn_flutter/assets/107464389/a22656ba-cdb2-4b3a-b254-004d76034f72)
![image](https://github.com/nizwar/openvpn_flutter/assets/107464389/d859a8d3-6b45-48b7-8e42-a1854edaed03)

**Comment by Spokplacenta** [comment]
OK I think my problem come from it 
<img width="975" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/5b241967-4cb8-46f6-8332-818aded52d26">
first time I resolved this error by deleting "VPNExtension.appex" from runner but I think it's a mistake.

**Comment by syedabdulbasit1** [comment]
It might be, but does this fix solve your issue

**Comment by Spokplacenta** [comment]
no I try to resolve the loop without deleting  "VPNExtension.appex" 

in the podfile how is implemented VPNExtension target 
<img width="883" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/0962242b-38cf-4011-92a2-d68930e7010b">
or 
<img width="834" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/4ffcb292-2041-476c-9885-fdf864b04344">
or it's not important ?

**Comment by Spokplacenta** [comment]
It's working !!! 
Probleme solved by changing order of the build phase.
I moved Thin Binary at the end of the Build Phases :
<img width="989" alt="image" src="https://github.com/nizwar/openvpn_flutter/assets/71837821/623efdfd-a4b9-4230-bd2b-9a00cb9af3df">

VPN is now connected on iOS too !

Thanks a lot @syedabdulbasit1 !

**Comment by syedabdulbasit1** [comment]
@Spokplacenta Thanks for acknowledge this issue. That's great 😊.
